### ISSUE TITLE
Trial data

### ISSUE THREAD

**Issue by sigven** [dfci/matchminer-engine#4]
Hi,

First, I apologize for filing an issue, this is really not a matchminer issue, but rather a way to get in touch with you (there is no contact info on the GitHub page, and neither at the [DFCI Knowledge Systems Group wepbage](http://bcb.dfci.harvard.edu/knowledge-systems/)

I came across your MatchMiner engine, which looks like a very promising solution for matching of genomic profiles to clinical trials. We are developing the [Personal Cancer Genome Reporter](http://github.com/sigven/pcgr), in which we would like also to add information with respect to ongoing clinical trials. Having looked briefly into the code and examples, I have one main question, which appear to be the main challenge as I see it: Do you have a framework for populating the clinical trial data (i.e. the clinical trial markup language (CTML)) with actual raw data from clinicaltrials.gov? You state in your [paper](http://ascopubs.org/doi/abs/10.1200/JCO.2017.35.15_suppl.6620) that 123 trials have been transformed to CTML. I could not see through the documentation how the clinical trial data (as CTML) is supposed to be retrieved/populated. I  am very much interested in how you plan to expand upon this number, as I consider this as the main limitation for the utility of the platform. Any feedback and/or suggestions for collaboration is appreciated (and you can safely close the issue)

regards,
Sigve Nakken

**Comment by thsteinmetz** [comment]
I would also be interested in knowing how you are populating your genomic data on a per trial basis.

**Comment by jim-bo** [comment]
Hi all, unfortunately most clinical trial protocols are protected by a non-disclosure agreement when the trial is opened at a cancer institute. A majority of the trials do not have any additional information in the private protocol that is available on https://www.clinicaltrials.gov/, but since we've curated our data internally from the private protocols we are not sure which is safe to share versus which is not. 

It is annoying and silly, but we've been advised that we cannot share the data until we've asserted no private information is being leaked. 

We can include some demo curations if that is helpful.
